import = [
    "~/.config/alacritty/theme_selected.toml"
]

[shell]
program = "tmux"

[env]
ALACRITTY_TERM = "true"

[font]
size = 12

[window]
dimensions = { columns = 120, lines = 45 }
title = "Terminal"
