import = [
    "~/.config/alacritty/theme_selected.toml"
]

[shell]
program = "tmux"

[env]
TERM = "xterm-256color"

[font]
size = 12

[window]
dimensions = { columns = 120, lines = 50 }
title = "Terminal"
