" vim-plug init
call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-commentary'
Plug 'ntpeters/vim-better-whitespace'
call plug#end()

" Plugins settings
"" vim-gitgutter transparent bg
highlight! link SignColumn LineNr

"" Variables
let g:airline_powerline_fonts = 1
let g:airline_left_sep        = ''
let g:airline_right_sep       = ''
let g:airline_left_alt_sep    = '|'
let g:airline_right_alt_sep   = '|'
let g:airline_theme = 'distinguished'
let g:airline#extensions#tabline#enabled = 1


" User settings

"" Options

""" Show line numbers
set number

""" Refresh time in ms
set updatetime=500

""" Allow unsaved buffers
set hidden

""" Prefer whitespace to tabs
set shiftwidth=4 smarttab
set tabstop=8 softtabstop=0


"" Keybinds

""" Remove all trailing whitespace
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

""" Unhighlight search
noremap <Leader><Space> :nohlsearch<CR>

""" Buffer Navigation
nnoremap <Leader>n :enew<CR>
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprev<CR>
nnoremap <Leader>3 :b#<CR>
nnoremap <Leader>a :only<CR>
nnoremap <Leader>b :ls<CR>
nnoremap Q :bd!<CR>
