" User settings

"" General
set term=xterm-256color

syntax on
set hidden
set hlsearch
set smartcase
set autoindent
set textwidth=80
set laststatus=2
set viminfo="NONE"
set relativenumber

set tabstop=8
set shiftwidth=4
set softtabstop=0
set expandtab smarttab

set fillchars+=vert:│

set list
set listchars=
set listchars+=tab:»\ 
set listchars+=trail:·
set listchars+=extends:»
set listchars+=precedes:«
set listchars+=nbsp:␣

""" Dynamic cursor
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

"" Highlight
highlight LineNr ctermfg=darkgrey
highlight MatchParen ctermbg=none cterm=bold
highlight WildMenu ctermfg=black ctermbg=white

highlight clear StatusLineNC
highlight StatusLine ctermbg=none cterm=bold
highlight StatusLineNC ctermbg=none ctermfg=gray

highlight clear VertSplit
highlight VertSplit ctermfg=white ctermbg=none

highlight Pmenu ctermbg=black ctermfg=white
highlight PmenuSel ctermbg=gray ctermfg=black

highlight clear SpellBad
highlight SpellBad cterm=underline


"" Keybinds

""" Set Leader key
let mapleader=" "

""" Remove all trailing whitespace
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

""" Unhighlight search
nnoremap <Esc> :nohlsearch<CR>

""" Buffers Navigation
nnoremap <Leader>n :bn<CR>
nnoremap <Leader>p :bp<CR>

""" Spelling check switches
nnoremap <Leader>l :set spell spelllang=en_us,ru_ru
nnoremap <Leader><S-l> :set nospell<CR>


" Features
"" Cross-platform clipboard without '+clipboard' dependency
function! ClipCopy(text) abort
    if executable('wl-copy')
        call system('wl-copy', a:text)
    elseif executable('xclip')
        call system('xclip -selection clipboard', a:text)
    elseif executable('termux-clipboard-set')
        call system('termux-clipboard-set', a:text)
    else
        echoerr 'No clipboard tool found'
    endif
endfunction

function! ClipPaste() abort
    if executable('wl-paste')
        return system('wl-paste --no-newline')
    elseif executable('xclip')
        return system('xclip -selection clipboard -o')
    elseif executable('termux-clipboard-get')
        return system('termux-clipboard-get')
    endif
    return ''
endfunction

xnoremap <silent> <Leader>y :<C-u>call ClipCopy(join(getline("'<","'>"), "\n"))<CR>
nnoremap <silent> <Leader>p :call append(line('.'), split(ClipPaste(), "\n"))<CR>
