" User settings

"" General Options
set term=xterm-256color
syntax on
set hlsearch
set autoindent
set textwidth=80
set updatetime=500

""" Relative numbers
set relativenumber
highlight LineNr ctermfg=darkgrey

""" Status line
set laststatus=2
hi StatusLine ctermbg=NONE cterm=bold

""" Allow unsaved buffers
set hidden

""" Disable registers caching
set viminfo="NONE"

""" Case insensitive when lowercase, sensitive if any uppercase
set smartcase

""" Disable delay for ESC
set timeout
set timeoutlen=50

""" Dynamic cursor
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

""" Spellcheck
hi clear SpellBad
hi SpellBad cterm=underline
hi SpellBad gui=undercurl

""" Prefer whitespace to tabs
set expandtab smarttab
set shiftwidth=4
set tabstop=8
set softtabstop=0

""" Visual clarity for whitespaces, tabs and other symbols.
set list
set listchars=
set listchars+=tab:»\ 
set listchars+=trail:·
set listchars+=extends:»
set listchars+=precedes:«
set listchars+=nbsp:␣


"" Keybinds

""" Set leader key
let mapleader=" "

""" Remove all trailing whitespace
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

""" Unhighlight search
nnoremap <Esc> :nohlsearch<CR>

""" Buffers Navigation
nnoremap <Leader>n :bn<CR>
nnoremap <Leader>p :bp<CR>

""" Spelling check switches
nnoremap <Leader>l :set spell spelllang=en_us,ru_ru
nnoremap <Leader><S-l> :set nospell<CR>
