vim.cmd.colorscheme("lunaperche")
vim.api.nvim_set_hl(0, 'Normal', { bg=none })
vim.api.nvim_set_hl(0, 'NonText', { bg=none })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { bg=none })
vim.api.nvim_set_hl(0, 'StatusLine', { bg=none })
