[icon]
globs = []
dirs = []
files = []
exts = []

[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
